### ISSUE TITLE
ios参考

### ISSUE THREAD

**Issue by linguitang** [yah0130/flutter_qrscaner#1]
[https://github.com/zxingify/zxingify-objc](https://github.com/zxingify/zxingify-objc)这个兴许对你有帮助

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by yah0130** [comment]
@linguitang 谢谢我看看先


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by linguitang** [comment]
[https://github.com/rodrigowerberich/barcode_platform_view](https://github.com/rodrigowerberich/barcode_platform_view)这个项目在跟你做一样的事
