### ISSUE TITLE
AndroidX的兼容问题?

### ISSUE THREAD

**Issue by lupming** [yah0130/flutter_qrscaner#2]
请问是否存在AndroidX的兼容问题??

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_qrscaner:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by liaohui1080** [comment]
有空帮忙解决一下呗

**Comment by yah0130** [comment]
> 有空帮忙解决一下呗

最近有点忙，之后再说吧

**Comment by liaohui1080** [comment]
> > 有空帮忙解决一下呗
> 
> 最近有点忙，之后再说吧

谢谢了

**Comment by yah0130** [comment]
> > > 有空帮忙解决一下呗
> > 
> > 
> > 最近有点忙，之后再说吧
> 
> 谢谢了

兼容了

**Comment by liaohui1080** [comment]
谢谢 我试试

发自我的iPad
